'use client';

import * as React from 'react';
import {
  Rocket,
  FileText,
  MessageSquare,
  Bell,
  CheckCircle2,
  User,
  Zap,
  Clock,
} from 'lucide-react';

interface ActivityEvent {
  id: string;
  type: 'mission_started' | 'mission_completed' | 'asset_generated' | 'message' | 'notification' | 'executive_assigned' | 'approval';
  title: string;
  subtitle: string;
  time: string;
}

const TYPE_CONFIG = {
  mission_started: { icon: Rocket, color: '#0A84FF', bg: 'bg-hq-blue/10' },
  mission_completed: { icon: CheckCircle2, color: '#22C55E', bg: 'bg-green-500/10' },
  asset_generated: { icon: FileText, color: '#0EA5E9', bg: 'bg-hq-cyan/10' },
  message: { icon: MessageSquare, color: '#8B5CF6', bg: 'bg-hq-purple/10' },
  notification: { icon: Bell, color: '#F59E0B', bg: 'bg-amber-500/10' },
  executive_assigned: { icon: User, color: '#EC4899', bg: 'bg-pink-500/10' },
  approval: { icon: Zap, color: '#10B981', bg: 'bg-emerald-500/10' },
};

// Demo feed data — real data comes from /api/analytics/activity
const DEMO_FEED: ActivityEvent[] = [
  { id: '1', type: 'mission_started', title: 'New mission launched', subtitle: 'Q3 Marketing Strategy assigned to CMO', time: '2m ago' },
  { id: '2', type: 'asset_generated', title: 'Asset created', subtitle: 'Brand guidelines PDF generated by CEO', time: '8m ago' },
  { id: '3', type: 'mission_completed', title: 'Mission delivered', subtitle: 'Financial report approved and archived', time: '22m ago' },
  { id: '4', type: 'executive_assigned', title: 'Executive assigned', subtitle: 'CFO assigned to Budget Review mission', time: '1h ago' },
  { id: '5', type: 'message', title: 'New conversation', subtitle: 'CTO responded in Tech Infrastructure thread', time: '1h ago' },
  { id: '6', type: 'approval', title: 'Approval granted', subtitle: 'COO approved Operations Expansion plan', time: '2h ago' },
  { id: '7', type: 'notification', title: 'Executive alert', subtitle: 'CEO flagged a critical strategic risk', time: '3h ago' },
];

interface GlobalActivityFeedProps {
  className?: string;
  maxItems?: number;
  compact?: boolean;
}

export function GlobalActivityFeed({ className = '', maxItems = 7, compact = false }: GlobalActivityFeedProps) {
  const items = DEMO_FEED.slice(0, maxItems);

  return (
    <div className={`space-y-1 ${className}`}>
      {items.map((event, i) => {
        const cfg = TYPE_CONFIG[event.type];
        const Icon = cfg.icon;
        return (
          <div
            key={event.id}
            className={`flex items-start gap-3 rounded-xl p-2.5 hover:bg-foreground/4 transition-colors cursor-pointer group ${
              compact ? 'py-2' : 'py-2.5'
            }`}
            style={{ animationDelay: `${i * 50}ms` }}
          >
            {/* Icon bubble */}
            <div className={`h-7 w-7 rounded-full ${cfg.bg} flex items-center justify-center shrink-0 mt-0.5`}>
              <Icon className="h-3.5 w-3.5" style={{ color: cfg.color }} />
            </div>

            {/* Content */}
            <div className="flex-1 min-w-0">
              <p className={`font-extrabold text-[#1A1A1E] dark:text-white truncate ${compact ? 'text-[10px]' : 'text-[11px]'}`}>
                {event.title}
              </p>
              <p className={`text-foreground/55 font-semibold truncate ${compact ? 'text-[9px]' : 'text-[10px]'}`}>
                {event.subtitle}
              </p>
            </div>

            {/* Time */}
            <div className="shrink-0 flex items-center gap-1 text-foreground/35 mt-0.5">
              <Clock className="h-2.5 w-2.5" />
              <span className="text-[9px] font-semibold">{event.time}</span>
            </div>
          </div>
        );
      })}
    </div>
  );
}
