'use client';

import * as React from 'react';
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
  Button,
  Input,
} from '@hq/ui';
import {
  FileText,
  Save,
  Sliders,
  Copy,
  CheckCircle,
  Sparkles,
  Download,
  Eye,
  Edit2,
  Trash2,
} from 'lucide-react';

interface CopyDoc {
  id: string;
  title: string;
  body: string;
  tone: string;
  updatedAt: string;
}

export default function ContentStudioPage() {
  const [docs, setDocs] = React.useState<CopyDoc[]>([
    {
      id: 'doc-1',
      title: 'Q3 Petroleum Outreach Proposal',
      body: 'Dear Board of Directors, we present the strategic B2B trade logistics proposal covering petroleum shipping corridors...',
      tone: 'Professional & Direct',
      updatedAt: '2 hours ago',
    },
    {
      id: 'doc-2',
      title: 'HQ Social Release Campaign',
      body: 'Say hello to HQ, the first AI Executive Operating System designed to automate and orchestrate corporate growth. Let your board work! 🚀',
      tone: 'Playful & Creative',
      updatedAt: '1 day ago',
    },
  ]);

  const [selectedId, setSelectedId] = React.useState<string>('doc-1');
  const [title, setTitle] = React.useState('');
  const [body, setBody] = React.useState('');
  const [tone, setTone] = React.useState('Professional & Direct');

  const [isCopied, setIsCopied] = React.useState(false);
  const [isSaved, setIsSaved] = React.useState(false);

  // Sync editor fields with selected document
  React.useEffect(() => {
    const doc = docs.find((d) => d.id === selectedId);
    if (doc) {
      setTitle(doc.title);
      setBody(doc.body);
      setTone(doc.tone);
    }
  }, [selectedId, docs]);

  const handleSave = () => {
    setDocs((prev) =>
      prev.map((d) =>
        d.id === selectedId ? { ...d, title, body, tone, updatedAt: 'Just now' } : d,
      ),
    );
    setIsSaved(true);
    setTimeout(() => setIsSaved(false), 2000);
  };

  const handleCreateNew = () => {
    const newDoc: CopyDoc = {
      id: `doc-${Date.now()}`,
      title: 'Untitled Document',
      body: '',
      tone: 'Professional & Direct',
      updatedAt: 'Just now',
    };
    setDocs((prev) => [newDoc, ...prev]);
    setSelectedId(newDoc.id);
  };

  const handleDelete = (id: string) => {
    setDocs((prev) => prev.filter((d) => d.id !== id));
    if (selectedId === id) {
      setSelectedId(docs[0]?.id || '');
    }
  };

  const handleCopyText = () => {
    navigator.clipboard.writeText(body);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  return (
    <div className="space-y-8 select-none">
      {/* Title */}
      <div className="flex flex-col space-y-2 md:flex-row md:items-center md:justify-between md:space-y-0">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-white flex items-center gap-2">
            <FileText className="h-8 w-8 text-hq-blue" />
            Content Studio Workspace
          </h1>
          <p className="text-foreground/60 text-sm mt-1">
            Compose, tune, and edit deliverables generated by your AI Executive Board.
          </p>
        </div>
        <Button
          variant="accent"
          className="flex items-center gap-1.5 text-xs h-9"
          onClick={handleCreateNew}
        >
          <Sparkles className="h-4 w-4" />
          Create Copy Template
        </Button>
      </div>

      <div className="grid gap-8 lg:grid-cols-4">
        {/* Left Side: Documents Directory */}
        <div className="lg:col-span-1 space-y-4">
          <Card className="border border-hq-graphite/40 bg-hq-graphite/20">
            <CardHeader className="pb-3">
              <CardTitle className="text-xs font-semibold uppercase tracking-wider text-foreground/50">
                Documents
              </CardTitle>
            </CardHeader>
            <CardContent className="p-3 space-y-2">
              {docs.map((doc) => {
                const isActive = doc.id === selectedId;
                return (
                  <div
                    key={doc.id}
                    onClick={() => setSelectedId(doc.id)}
                    className={`flex items-start justify-between p-2.5 rounded-md cursor-pointer transition-all border ${
                      isActive
                        ? 'bg-hq-blue/10 border-hq-blue/30 text-white'
                        : 'bg-transparent border-transparent hover:bg-hq-graphite/10 text-foreground/75'
                    }`}
                  >
                    <div className="space-y-0.5 min-w-0 pr-2">
                      <p className="text-xs font-bold truncate">{doc.title || 'Untitled'}</p>
                      <p className="text-[9px] text-foreground/45">Saved: {doc.updatedAt}</p>
                    </div>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleDelete(doc.id);
                      }}
                      className="text-foreground/40 hover:text-red-400 p-0.5 shrink-0"
                    >
                      <Trash2 className="h-3 w-3" />
                    </button>
                  </div>
                );
              })}
            </CardContent>
          </Card>
        </div>

        {/* Center: Copywriting Editor */}
        <div className="lg:col-span-2 space-y-6">
          <Card className="border border-hq-graphite/40 bg-hq-graphite/20 flex flex-col h-[520px]">
            <CardHeader className="border-b border-hq-graphite/20 pb-4">
              <div className="flex items-center justify-between">
                <CardTitle className="text-sm flex items-center gap-1.5">
                  <Edit2 className="h-4 w-4 text-hq-blue" />
                  Editor Pane
                </CardTitle>
                <div className="flex gap-2">
                  <Button
                    variant="ghost"
                    size="icon"
                    className="h-8 w-8 text-foreground/60"
                    onClick={handleCopyText}
                  >
                    {isCopied ? (
                      <CheckCircle className="h-4 w-4 text-hq-cyan animate-pulse" />
                    ) : (
                      <Copy className="h-4 w-4" />
                    )}
                  </Button>
                  <Button variant="ghost" size="icon" className="h-8 w-8 text-foreground/60">
                    <Download className="h-4 w-4" />
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent className="flex-1 p-6 flex flex-col space-y-4">
              <div className="space-y-1.5">
                <label className="text-[10px] font-semibold text-foreground/50 uppercase tracking-wider">
                  Document Title
                </label>
                <Input value={title} onChange={(e) => setTitle(e.target.value)} className="h-9" />
              </div>

              <div className="flex-1 flex flex-col space-y-1.5">
                <label className="text-[10px] font-semibold text-foreground/50 uppercase tracking-wider">
                  Body Text Content
                </label>
                <textarea
                  value={body}
                  onChange={(e) => setBody(e.target.value)}
                  className="flex-1 w-full rounded-md border border-hq-graphite/40 bg-hq-graphite/30 p-3 text-xs focus:outline-none focus:ring-1 focus:ring-hq-blue text-foreground font-sans resize-none"
                  placeholder="Enter copywriting text content..."
                />
              </div>
            </CardContent>
            <CardFooter className="border-t border-hq-graphite/20 p-4 flex justify-between items-center bg-hq-graphite/10">
              <span className="text-[10px] text-foreground/50 font-mono">
                {body.length} characters | {body.split(/\s+/).filter(Boolean).length} words
              </span>
              <div className="flex items-center gap-2">
                {isSaved && (
                  <span className="text-[10px] text-hq-cyan font-semibold animate-pulse">
                    ✓ Saved
                  </span>
                )}
                <Button
                  variant="primary"
                  size="sm"
                  className="h-8 text-xs flex items-center gap-1"
                  onClick={handleSave}
                >
                  <Save className="h-3.5 w-3.5" />
                  Save Draft
                </Button>
              </div>
            </CardFooter>
          </Card>
        </div>

        {/* Right Side: Tone adjustments details and Document Previews */}
        <div className="lg:col-span-1 space-y-6">
          {/* Tone config sliders */}
          <Card>
            <CardHeader>
              <CardTitle className="text-sm flex items-center gap-1.5">
                <Sliders className="h-4 w-4 text-hq-purple" />
                Tone Adjuster
              </CardTitle>
              <CardDescription>Adjust generated copywriting characteristics</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4 text-xs">
              <div className="space-y-1.5">
                <label className="text-foreground/75 font-semibold">Creative Tone Preset</label>
                <select
                  value={tone}
                  onChange={(e) => setTone(e.target.value)}
                  className="h-9 w-full rounded-md border border-hq-graphite/40 bg-hq-graphite/30 px-3 text-sm text-foreground focus:outline-none"
                >
                  <option value="Professional & Direct">Professional & Direct</option>
                  <option value="Analytical & Technical">Analytical & Technical</option>
                  <option value="Playful & Creative">Playful & Creative</option>
                </select>
              </div>
            </CardContent>
          </Card>

          {/* Document Preview Card rendering */}
          <Card className="border border-hq-cyan/20 bg-hq-cyan/5">
            <CardHeader className="pb-2">
              <CardTitle className="text-xs font-semibold uppercase tracking-wider text-hq-cyan flex items-center gap-1.5">
                <Eye className="h-4 w-4" />
                Live Preview
              </CardTitle>
            </CardHeader>
            <CardContent className="p-4 space-y-3">
              <div className="border border-hq-graphite/40 bg-[#0A0A0C] rounded p-3 space-y-1.5">
                <p className="text-[10px] font-bold text-white uppercase tracking-wider">
                  Preview Document Render
                </p>
                <h4 className="text-xs font-bold text-white">{title || 'Untitled'}</h4>
                <p className="text-[10px] text-foreground/75 leading-relaxed line-clamp-4">
                  {body || 'Awaiting editor entries...'}
                </p>
              </div>
              <p className="text-[9px] text-foreground/45 leading-relaxed">
                This is a live representation of the formatted text that will be generated for
                campaigns or proposals.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
